services:
  mysql:
    image: mysql:latest
    container_name: hospital-db
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: hospital
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hospital-network

volumes:
  db_data:

networks:
  hospital-network:
    driver: bridge
